from ubuntu:focal

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /tmp

RUN apt-get update
RUN apt-get -y install git curl unzip tree jq debhelper

RUN bash -c "$(curl -fsSL https://gist.githubusercontent.com/TaylorMonacelli/518fc257340d486a2b403b490f535bcf/raw/aa7dae078c0dad66f84349a491fea44ab6bb1a03/ripgrep_linux.sh)"

RUN apt-get clean

CMD ["sleep", "1"]
