from ubuntu:focal

WORKDIR /tmp

RUN apt-get update
RUN apt-get -y install git curl unzip tree jq

RUN curl -sLo /tmp/ripgrep.sh https://gist.githubusercontent.com/TaylorMonacelli/518fc257340d486a2b403b490f535bcf/raw/aa7dae078c0dad66f84349a491fea44ab6bb1a03/ripgrep_linux.sh
RUN bash /tmp/ripgrep.sh

CMD ["sleep", "1"]
