from ubuntu:focal

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /tmp

RUN apt-get update
RUN apt-get -y install git curl unzip tree jq debhelper

RUN bash -c "$(curl -fsSL https://gist.githubusercontent.com/TaylorMonacelli/518fc257340d486a2b403b490f535bcf/raw/110f30a818b496aa7c68d65c3fe91ebedab871c6/ripgrep_linux.sh)"

RUN apt-get clean

CMD ["sleep", "1"]
